name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Unit tests
        run: bundle exec fastlane unit_test
